"""empty message

Revision ID: 731438255690
Revises: cc1651b7331f
Create Date: 2020-09-18 16:03:39.107925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731438255690'
down_revision = 'cc1651b7331f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nonce', sa.String(length=255), nullable=False))
    op.drop_column('users', 'noonce')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('noonce', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'nonce')
    # ### end Alembic commands ###
